### ISSUE TITLE
Add tests to validate the structure of the gosling object [1MD]

### ISSUE THREAD

**Issue by vedhav** [Appsilon/shiny.gosling#104]
Test to check JSON output structure that is in line with the documentation of gosling.js
Snapshot testing

Also, snapshot tests, https://testthat.r-lib.org/articles/snapshotting.html#whole-file-snapshotting

**Comment by federiva** [comment]
>Test to check JSON output structure that is in line with the documentation of gosling.js

The aforementioned will be addressed directly via #105 as we consider that it will be more maintainable to catch errors with the JS library
