### ISSUE TITLE
Make sure the track data works for json [2MD]

### ISSUE THREAD

**Issue by vedhav** [Appsilon/shiny.gosling#99]
Using the data source type as `json` did not work. The potential for this data source is huge because it might allow us to use in-memory data as a source for the gosling plot.
A good start would be to reproduce this simple plot from the gosling examples: [https://gosling.js.org/?example=RULE](https://gosling.js.org/?example=RULE)

**Comment by jakubnowicki** [comment]
Possibly going to be fixed by #98

**Comment by anirbanshaw24** [comment]
Fixed and working.
